mkdir -p .github/workflows
cat > .github/workflows/ci.yml <<'YAML'
name: Hola Mundo

on: push

jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir saludo
        run: echo "¡Hola desde GitHub Actions!"
YAML
